const airports = [
   {  
      "iataCode":"UDR",
      "airportName":"Udaipur",
      "cityName":"Udaipur",
      "countryCode":"IN",
      "isAllAirport":false,
      "airports":null,
      "isMain":false,
      "cityId":"1059473",
      "timeZone":"Asia\/Kolkata"
   },
   {  
      "iataCode":"DED",
      "airportName":"Jolly Grant Airport",
      "cityName":"Dehradun",
      "countryCode":"IN",
      "isAllAirport":false,
      "airports":null,
      "isMain":false,
      "cityId":"1088085",
      "timeZone":"Asia\/Kolkata"
   },{  
      "iataCode":"IXU",
      "airportName":"Aurangabad",
      "cityName":"Aurangabad",
      "countryCode":"IN",
      "isAllAirport":false,
      "airports":null,
      "isMain":false,
      "cityId":"1078022",
      "timeZone":"Asia\/Kolkata"
   },{  
      "iataCode":"BHO",
      "airportName":"Bairagarh Airport",
      "cityName":"Bhopal",
      "countryCode":"IN",
      "isAllAirport":false,
      "airports":null,
      "isMain":false,
      "cityId":"1076183",
      "timeZone":"Asia\/Kolkata"
   },{  
      "iataCode":"BLR",
      "airportName":"Kempegowda International Airport",
      "cityName":"Bengaluru",
      "countryCode":"IN",
      "isAllAirport":false,
      "airports":null,
      "isMain":false,
      "cityId":"1077380",
      "timeZone":"Asia\/Kolkata"
   },{  
      "iataCode":"MAA",
      "airportName":"Chennai International Airport",
      "cityName":"Chennai",
      "countryCode":"IN",
      "isAllAirport":false,
      "airports":null,
      "isMain":false,
      "cityId":"1067561",
      "timeZone":"Asia\/Kolkata"
   },{  
      "iataCode":"DEL",
      "airportName":"Delhi",
      "cityName":"Delhi",
      "countryCode":"IN",
      "isAllAirport":false,
      "airports":null,
      "isMain":false,
      "cityId":"1059156",
      "timeZone":"Asia\/Kolkata"
   },{  
      "iataCode":"LKO",
      "airportName":"Amausi Airport",
      "cityName":"Lucknow",
      "countryCode":"IN",
      "isAllAirport":false,
      "airports":null,
      "isMain":false,
      "cityId":"1067712",
      "timeZone":"Asia\/Kolkata"
   },{  
      "iataCode":"HYD",
      "airportName":"Rajiv Gandhi International Airport",
      "cityName":"Hyderabad",
      "countryCode":"IN",
      "isAllAirport":false,
      "airports":null,
      "isMain":false,
      "cityId":"1071678",
      "timeZone":"Asia\/Kolkata"
   },{  
      "iataCode":"PNQ",
      "airportName":"Lohegaon Air Force Base",
      "cityName":"Pune",
      "countryCode":"IN",
      "isAllAirport":false,
      "airports":null,
      "isMain":false,
      "cityId":"1063489",
      "timeZone":"Asia\/Kolkata"
   },{  
      "iataCode":"JAI",
      "airportName":"Sanganer Airport",
      "cityName":"Jaipur",
      "countryCode":"IN",
      "isAllAirport":false,
      "airports":null,
      "isMain":false,
      "cityId":"1071423",
      "timeZone":"Asia\/Kolkata"
   },{  
      "iataCode":"CCU",
      "airportName":"Netaji Subhash Chandra Bose Intl Airport",
      "cityName":"Kolkata",
      "countryCode":"IN",
      "isAllAirport":false,
      "airports":null,
      "isMain":false,
      "cityId":"1075562",
      "timeZone":"Asia\/Kolkata"
   },{  
      "iataCode":"RPR",
      "airportName":"Raipur",
      "cityName":"Raipur",
      "countryCode":"IN",
      "isAllAirport":false,
      "airports":null,
      "isMain":false,
      "cityId":"1063292",
      "timeZone":"Asia\/Kolkata"
   },{  
      "iataCode":"IXC",
      "airportName":"Chandigarh Air Force Base",
      "cityName":"Chandigarh",
      "countryCode":"IN",
      "isAllAirport":false,
      "airports":null,
      "isMain":false,
      "cityId":"1075379",
      "timeZone":"Asia\/Kolkata"
   },{  
      "iataCode":"NAG",
      "airportName":"Dr. Babasaheb Ambedkar International Airport",
      "cityName":"Nagpur",
      "countryCode":"IN",
      "isAllAirport":false,
      "airports":null,
      "isMain":false,
      "cityId":"1065783",
      "timeZone":"Asia\/Kolkata"
   },{  
      "iataCode":"IDR",
      "airportName":"Devi Ahilyabai Holkar International Airport",
      "cityName":"Indore",
      "countryCode":"IN",
      "isAllAirport":false,
      "airports":null,
      "isMain":false,
      "cityId":"1071602",
      "timeZone":"Asia\/Kolkata"
   },{  
      "iataCode":"AMD",
      "airportName":"Sardar Vallabhbhai Patel International Airport",
      "cityName":"Ahmedabad",
      "countryCode":"IN",
      "isAllAirport":false,
      "airports":null,
      "isMain":false,
      "cityId":"1078853",
      "timeZone":"Asia\/Kolkata"
   },{  
      "iataCode":"TRV",
      "airportName":"Thiruvananthapuram International Airport",
      "cityName":"Thiruvananthapuram",
      "countryCode":"IN",
      "isAllAirport":false,
      "airports":null,
      "isMain":false,
      "cityId":"1059593",
      "timeZone":"Asia\/Kolkata"
   },{  
      "iataCode":"VNS",
      "airportName":"Varanasi",
      "cityName":"Varanasi",
      "countryCode":"IN",
      "isAllAirport":false,
      "airports":null,
      "isMain":false,
      "cityId":"1059025",
      "timeZone":"Asia\/Kolkata"
   },{  
      "iataCode":"CJB",
      "airportName":"Coimbatore Airport",
      "cityName":"Coimbatore",
      "countryCode":"IN",
      "isAllAirport":false,
      "airports":null,
      "isMain":false,
      "cityId":"1074704",
      "timeZone":"Asia\/Kolkata"
   },{  
      "iataCode":"ATQ",
      "airportName":"Raja Sansi International Airport",
      "cityName":"Amritsar",
      "countryCode":"IN",
      "isAllAirport":false,
      "airports":null,
      "isMain":false,
      "cityId":"1078444",
      "timeZone":"Asia\/Kolkata"
   }
]
export default airports;